CXX = g++
CXXFLAGS = -std=c++11 -Wall -Wextra

SRCDIR = src
OBJDIR = obj
BINDIR = bin

SRCS = $(wildcard $(SRCDIR)/*.cpp)
OBJS = $(patsubst $(SRCDIR)/%.cpp, $(OBJDIR)/%.o,$(SRCS))
EXEC = $(BINDIR)/main

all: $(EXEC)

$(EXEC) : $(OBJS)
		$(CXX) $(CXXFLAGS) $^ -o $@

$(OBJDIR)/%.o: $(SRCDIR)/%.cpp
		@mkdir -p $(@D)
		$(CXX) $(CXXFLAGS) -c $< -o $@
clean:
		rm -rf $(OBJDIR) $(BINDIR)

.PHONY: all clean

